sudo: required
dist: trusty
jdk:
- openjdk11
script:
- mvn clean package
- mvn sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

deploy:
  provider: script
  script: "mvn heroku:deploy"
  skip_cleanup: true
  on:
    branch: master